(defun opstr (op funct)
    (case op
        (#b000 (case funct 
            (#b000 'ADD)
            (#b001 'SLL)
            (#b010 'SRL)
            (#b011 'SLT)
            (#b100 'SLTU)
            (#b101 'XOR)
            (#b110 'OR)
            (#b111 'AND)
        ))
        (#b001 'Invalid)
        (#b010 (case funct 
            (#b000 'FADD)
            (#b001 'FSUB)
            (#b010 'FMUL)
            (#b011 'FDIV)
            (#b100 'FSQRT)
            (#b101 'FNEG)
            (#b110 'FMIN)
            (#b111 'FMAX)
        ))
        (#b011 (case funct 
            (#b000 'FEQ)
            (#b001 'FLT)
            (#b010 'FLE)
            (#b011 'FMV.X.W)
            (#b100 'FMV.W.X)
            (#b101 'FMV)
            (#b110 'ITOF)
            (#b111 'FTOI)
        ))
        (#b100 (case funct 
            (#b000 'ADDI)
            (#b001 'SLLI)
            (#b010 'SRLI)
            (#b011 'SLTI)
            (#b100 'SLTUI)
            (#b101 'XORI)
            (#b110 'ORI)
            (#b111 'ANDI)
        ))
        (#b101 (case funct 
            (#b000 'LW)
            (#b001 'FLW)
            (#b010 'LUI)
            (#b011 'INVALID)
            (#b100 'SWI)
            (#b101 'INVALID)
            (#b110 'INVALID)
            (#b111 'INVALID)
        ))
        (#b110 (case funct 
            (#b000 'BEQ)
            (#b001 'BNE)
            (#b010 'BLT)
            (#b011 'BGE)
            (#b100 'BLTU)
            (#b101 'BGEU)
            (#b110 'SW)
            (#b111 'FSW)
        ))
        (#b111 (case funct 
            (#b000 'JUMP)
            (#b001 'JAL)
            (#b010 'JALR)
            (#b011 'INVALID)
            (#b100 'INVALID)
            (#b101 'INVALID)
            (#b110 'INVALID)
            (#b111 'INVALID)
        ))

    )
)
(defun dis (inst)
    (let ((op (logand inst #b111))
          (funct (logand (ash inst -3) #b111))
          (immIL (logand (ash inst -6) #xffff))
          (immSB (logand (ash inst -11)#xffff))
          (jaddr (logand (ash inst -6)#x1ffffff))
          (rs1   (logand (ash inst -27)#b11111))
          (rs2   (logand (ash inst -6)#b11111))
          (rd    (logand (ash inst -22)#b11111)))
          (list (opstr op funct) 'rs1 rs1 'rs2 rs2 'rd rd 'immIL immIL 'immSB immSB 'jaddr jaddr)))